name: debug-new-features

on:
  push:
    branches: ["main", "develop", "feature/*"]
  workflow_dispatch:

jobs:
  skip-reason-test:
    if: ${{ github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: This only runs on main
        run: echo "Hello from Main branch!"
