name: test-workflow

on:
  push:
    branches: [ "main", "develop", "*" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Display branch specific message
        run: |
          echo "${case(github.ref_name, 'main', 'Production環境へデプロイを開始します', 'develop', 'Staging環境でテストを実行します', 'ローカルブランチで作業中です')}"
